[default]
extend-ignore-re = [
    "(?Rm)^.*(#|//)\\s*spellchecker:\\s*disable-line$",
    "(?s)(#|//)\\s*spellchecker:\\s*off.*?\\n\\s*(#|//)\\s*spellchecker:\\s*on",
    "(#|//)\\s*spellchecker:\\s*ignore-next-line\\n.*"
]
[default.extend-words]
oder = "oder"
