[project]
authors = ["Alexander Ivanov <alexander.valentinov.ivanov@gmail.com>"]
channels = ["conda-forge"]
description = "An sdk for Duden API"
name = "duden_sdk"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13"


[feature.test.dependencies]
pytest = "*"

[environments]
test = ["test"]
