[project]
authors = ["Alexander Ivanov <alexander.valentinov.ivanov@gmail.com>"]
channels = ["conda-forge"]
description = "An sdk for Duden API"
name = "duden_cli"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
editable = "pixi run pip install --no-build-isolation --editable ."
duden = "pixi run -e default python duden_cli/cli.py"

[dependencies]
python = ">=3.13"
pydantic = ">=2.11.7,<3"
pydantic-settings = ">=2.10.1,<3"
typer = ">=0.16.0,<0.17"
httpx = ">=0.28.1,<0.29"
pip = ">=25.1.1,<26"
beautifulsoup4 = ">=4.13.4,<5"
markdownify = ">=0.14.1,<0.15"
prettytable = ">=3.16.0,<4"
structlog = ">=25.4.0,<26"
genanki = ">=0.13.1,<0.14"
rich = ">=14.1.0,<15"


[feature.test.dependencies]
pytest = ">=8.4.1,<9"
pytest-mock = ">=3.14.1,<4"
pytest-cov = ">=6.2.1,<7"

[feature.test.tasks]
test = "pixi run -e test pytest"

[feature.build.dependencies]
python-build = "*"
pip = "*"
hatchling = "*"
hatch-vcs = "*"

[feature.lint.dependencies]
docformatter = "*"
ruff = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
pre-commit = ">=4.2.0,<5"
mypy = ">=1.16.1,<2"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
default = { features = ["test", "build"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
build = { features = ["build"], solve-group = "default" }
lint = { features = ["lint", "build"], no-default-feature = true }
